/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/recommendation/questions/{experience_level}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 취향 테스트 문항 6개 받아오기
         * @description **언제 호출하나** — 사용자가 시작 화면에서 입문자/경험자를 고른 직후, 테스트당 한 번만 호출합니다.
         *
         *     **무엇이 오나** — 6개 문항이 한 번에 옵니다. 문항마다 4개의 선택지가 들어 있고, `question_id`(1~6)와 `choice_id`(1~4)는 나중에 답을 제출할 때 그대로 다시 보내야 하는 값입니다.
         *
         *     문항을 하나씩 요청하는 API는 없습니다. 받아온 6문항을 프론트가 순서대로 보여주면서 사용자의 선택을 모아두었다가, 마지막에 `POST /api/recommendation/submit` 으로 한 번에 제출하세요.
         *
         *     `progress` 는 그 문항까지 왔을 때의 진행률(%)이라 진행 바에 그대로 쓸 수 있습니다. (1번 문항 16.7 → 6번 문항 100.0)
         *
         *     **두 문항 세트의 차이** — 문항 수와 구조는 같고 표현만 다릅니다. `beginner` 는 평양냉면이 처음인 사람도 답할 수 있게 일반적인 음식 취향을 묻고, `expert` 는 육수·면발 같은 용어를 그대로 씁니다.
         */
        get: operations["get_recommendation_questions_api_recommendation_questions__experience_level__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recommendation/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 답변을 제출하고 결과 화면 데이터 받기
         * @description **언제 호출하나** — 사용자가 6문항을 모두 답한 뒤 한 번만 호출합니다. 이 API 하나로 취향 유형 판정과 가게 추천이 동시에 끝납니다.
         *
         *     **무엇을 보내나** — 앞서 받아온 문항의 `question_id` 와 사용자가 고른 `choice_id` 짝을 `answers` 배열에 담아 보냅니다. 6문항 전부 채워 보내세요.
         *
         *     **무엇이 오나** — 결과 화면 하나를 그릴 재료가 전부 들어 있어서, 추가 호출이 필요 없습니다.
         *
         *     - `primary_type` — 대표 유형. 제목·부제·배지·설명 문구와 테마 색까지 들어 있어 그대로 화면에 쓰면 됩니다. 문구를 서버에서 내려주므로 프론트에 유형별 텍스트를 하드코딩하지 마세요.
         *     - `secondary_type` / `farthest_type` — 2순위 유형과 가장 안 맞는 유형. 이름과 캐릭터만 들어 있습니다.
         *     - `type_scores` — 4개 유형 전체의 일치도. 막대 그래프용입니다.
         *     - `taste_profile` — 육향·감칠맛·메밀향·산미 4축 점수(1~5). 축 이름(`label`)도 함께 오므로 그래프 축 이름을 프론트에 적어둘 필요가 없습니다.
         *     - `recommended_restaurants` — 추천 가게 2곳. 순위, 추천 이유 문장, 주소, 지도 링크가 들어 있습니다.
         *
         *     **가게가 없을 수 있습니다** — `status` 가 `no_recommendation` 이면 `recommended_restaurants` 가 빈 배열로 오고 `message` 에 안내 문구가 담깁니다. 이때도 유형 판정과 취향 그래프는 정상적으로 채워지므로, 가게 목록 영역만 비우고 나머지 결과는 그대로 보여주면 됩니다.
         *
         *     **`session_id` 는 선택입니다** — 프론트가 만든 익명 UUID를 넣으면 같은 사용자의 응답을 묶어 유형 분포를 집계할 수 있습니다. 로그인과 무관하며 개인정보를 넣어서는 안 됩니다. 생략해도 결과는 같습니다.
         */
        post: operations["submit_recommendation_api_recommendation_submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * PrimaryType
         * @description 대표 유형. 결과 화면 상단 카드에 필요한 카피를 모두 포함한다.
         *
         *     문구가 모두 서버에서 오므로 프론트에 유형별 텍스트를 하드코딩하지 않는다.
         *     카피를 고칠 때 서버만 배포하면 되도록 한 구조다.
         */
        PrimaryType: {
            /**
             * Key
             * @description 유형 키. 캐릭터 이미지 등 프론트 리소스를 고르는 기준으로 쓴다.
             * @enum {string}
             */
            key: "uraeok" | "uijeongbu" | "jangchungdong" | "dongchimi";
            /**
             * Name
             * @description 화면에 노출할 유형 이름. 예: `우래옥형`.
             */
            name: string;
            /**
             * Character Key
             * @description 캐릭터 이미지 키. 현재는 `key` 와 같은 값이 온다.
             */
            character_key: string;
            /**
             * Match Score
             * @description 이 유형과의 일치도(0.0~1.0). 백분율로 바꿔 표시한다.
             */
            match_score: number;
            /**
             * Title
             * @description 결과 카드 제목. 예: `진하고 든든한 우래옥형`.
             */
            title: string;
            /**
             * Subtitle
             * @description 제목 아래 한 줄 설명.
             */
            subtitle: string;
            /**
             * Badge
             * @description 카드에 붙는 짧은 배지 문구.
             */
            badge: string;
            /**
             * Reason
             * @description 이 유형으로 판정된 이유를 설명하는 본문(2~3문장).
             */
            reason: string;
            /**
             * Theme Color
             * @description 결과 카드에 쓸 테마 색상 HEX 코드. 예: `#C98A3C`.
             */
            theme_color: string;
        };
        /**
         * RecommendationAnswer
         * @description 사용자가 문항 하나에 답한 결과.
         */
        RecommendationAnswer: {
            /**
             * Question Id
             * @description 답한 문항 번호. 문항 조회 응답의 `question_id` 를 그대로 쓴다.
             */
            question_id: number;
            /**
             * Selected Choice Id
             * @description 사용자가 고른 선택지 번호. 문항 조회 응답의 `choice_id` 를 그대로 쓴다.
             */
            selected_choice_id: number;
        };
        /**
         * RecommendationChoice
         * @description 문항 하나에 딸린 선택지.
         */
        RecommendationChoice: {
            /**
             * Choice Id
             * @description 선택지 번호(1~4). 사용자가 이 선택지를 고르면 답변 제출 시 `selected_choice_id` 로 그대로 보낸다.
             */
            choice_id: number;
            /**
             * Choice Text
             * @description 화면에 그대로 노출할 선택지 문구.
             */
            choice_text: string;
        };
        /**
         * RecommendationQuestion
         * @description 취향 테스트 문항 하나.
         */
        RecommendationQuestion: {
            /**
             * Question Id
             * @description 문항 번호(1~6). 답변 제출 시 그대로 다시 보낸다.
             */
            question_id: number;
            /**
             * Question Text
             * @description 화면에 그대로 노출할 질문 문구.
             */
            question_text: string;
            /**
             * Choices
             * @description 선택지 4개. 배열 순서대로 보여주면 된다.
             */
            choices: components["schemas"]["RecommendationChoice"][];
            /**
             * Progress
             * @description 이 문항까지 왔을 때의 진행률(%). 진행 바에 그대로 쓴다. 1번 16.7 ~ 6번 100.0.
             */
            progress: number;
        };
        /**
         * RecommendationQuestionsResponse
         * @description 문항 조회 응답. 6문항이 한 번에 온다.
         */
        RecommendationQuestionsResponse: {
            /**
             * Experience Level
             * @description 요청한 문항 세트 종류를 그대로 돌려준다.
             * @enum {string}
             */
            experience_level: "beginner" | "expert";
            /**
             * Questions
             * @description 문항 6개. 배열 순서가 곧 출제 순서다.
             */
            questions: components["schemas"]["RecommendationQuestion"][];
        };
        /**
         * RecommendationResultResponse
         * @description 결과 화면 전체를 한 번에 그릴 수 있는 응답.
         *
         *     유형 판정과 취향 그래프는 사용자 답변만으로 계산되므로 가게 데이터와
         *     무관하게 항상 채워진다. 가게 추천만 비어 있을 수 있다.
         */
        RecommendationResultResponse: {
            /**
             * Status
             * @description `recommended` 면 추천 가게가 담겨 있고, `no_recommendation` 이면 `recommended_restaurants` 가 빈 배열이다. 후자여도 유형과 그래프는 정상이므로 가게 목록 영역만 비우고 나머지는 그대로 보여주면 된다.
             * @enum {string}
             */
            status: "recommended" | "no_recommendation";
            /**
             * Message
             * @description 추천할 가게가 없을 때의 안내 문구. 추천이 있으면 null이다.
             */
            message?: string | null;
            /**
             * Experience Level
             * @description 요청에 담겨 온 값을 그대로 돌려준다.
             * @enum {string}
             */
            experience_level: "beginner" | "expert";
            /** @description 대표 유형. 결과 화면 상단 카드에 필요한 문구가 모두 들어 있다. */
            primary_type: components["schemas"]["PrimaryType"];
            /** @description 2순위 유형. 이름과 캐릭터만 노출한다. */
            secondary_type: components["schemas"]["TypeSummary"];
            /** @description 가장 거리가 먼 유형. `이런 맛은 덜 맞아요` 식의 대비 노출에 쓴다. */
            farthest_type: components["schemas"]["TypeSummary"];
            /**
             * Type Scores
             * @description 4개 유형 전체의 일치도. 일치도 내림차순으로 온다.
             */
            type_scores: components["schemas"]["TypeScore"][];
            /** @description 사용자 취향의 4축 점수. 취향 그래프에 쓴다. */
            taste_profile: components["schemas"]["TasteProfile"];
            /**
             * Recommended Restaurants
             * @description 적합도 순으로 정렬된 추천 가게 목록. 기본 2곳이며 비어 있을 수 있다.
             */
            recommended_restaurants: components["schemas"]["RecommendedRestaurant"][];
        };
        /**
         * RecommendationSubmitRequest
         * @description 답변 제출 요청. 6문항을 모두 답한 뒤 한 번에 보낸다.
         */
        RecommendationSubmitRequest: {
            /**
             * Experience Level
             * @description 문항을 받아올 때 쓴 값과 같아야 한다.
             * @enum {string}
             */
            experience_level: "beginner" | "expert";
            /**
             * Answers
             * @description 6문항의 답변. 순서는 상관없다.
             */
            answers: components["schemas"]["RecommendationAnswer"][];
            /**
             * Session Id
             * @description 프론트가 만든 익명 식별자(UUID 등). 통계 집계용이며 생략해도 결과는 같다. 로그인과 무관하고 개인정보를 담아서는 안 된다.
             */
            session_id?: string | null;
        };
        /**
         * RecommendedRestaurant
         * @description 추천 가게 한 곳.
         */
        RecommendedRestaurant: {
            /**
             * Rank
             * @description 추천 순위. 1부터 시작한다.
             */
            rank: number;
            /**
             * Restaurant Name
             * @description 가게 이름.
             */
            restaurant_name: string;
            /**
             * Fit Score
             * @description 사용자 취향과의 적합도(0.0~1.0).
             */
            fit_score: number;
            /**
             * Type Key
             * @description 이 가게가 속한 취향 유형. 분류되지 않은 가게는 null.
             */
            type_key?: ("uraeok" | "uijeongbu" | "jangchungdong" | "dongchimi") | null;
            /**
             * Fit Sentence
             * @description 이 가게를 추천하는 이유 한 문장. 카드에 그대로 노출한다.
             */
            fit_sentence: string;
            /**
             * Evidence Summary
             * @description 추천 근거 요약. 리뷰에서 추출한 맛 특징 설명이다.
             */
            evidence_summary: string;
            /**
             * Scores
             * @description 가게의 4축 점수. 키는 `taste_profile` 의 축 키와 같아서 사용자 취향과 겹쳐 그릴 수 있다.
             */
            scores: {
                [key: string]: number;
            };
            /**
             * Address
             * @description 가게 주소. 수집 전인 가게는 null.
             */
            address?: string | null;
            /**
             * Map Url
             * @description 지도 링크. 아직 수집되지 않은 가게는 임시 링크가 내려오므로, 버튼 노출 여부는 이 값으로 판단하지 않는다.
             */
            map_url?: string | null;
        };
        /**
         * TasteProfile
         * @description 사용자의 취향을 4개 축으로 나타낸 그래프 데이터.
         */
        TasteProfile: {
            /**
             * @description 그래프 눈금 범위(1~5).
             * @default {
             *       "min": 1,
             *       "max": 5
             *     }
             */
            scale: components["schemas"]["TraitScale"];
            /**
             * Traits
             * @description 4개 축의 점수. 육향·감칠맛·메밀향·산미 순으로 온다.
             */
            traits: components["schemas"]["TraitScore"][];
        };
        /**
         * TraitScale
         * @description 취향 그래프 축의 눈금 범위. 그래프 최소·최대값을 이 값으로 잡는다.
         */
        TraitScale: {
            /**
             * Min
             * @description 축 최소값. 항상 1.0이다.
             * @default 1
             */
            min: number;
            /**
             * Max
             * @description 축 최대값. 항상 5.0이다.
             * @default 5
             */
            max: number;
        };
        /**
         * TraitScore
         * @description 맛 축 하나의 점수.
         */
        TraitScore: {
            /**
             * Key
             * @description 축 키. `meat_aroma`(육향) / `umami`(감칠맛) / `buckwheat_aroma`(메밀향) / `acidity`(산미).
             * @enum {string}
             */
            key: "meat_aroma" | "umami" | "buckwheat_aroma" | "acidity";
            /**
             * Label
             * @description 화면에 노출할 축 이름. 예: `육향`. 프론트에 축 이름을 적어둘 필요가 없다.
             */
            label: string;
            /**
             * Score
             * @description 해당 축의 취향 점수(1.0~5.0). 높을수록 그 맛을 선호한다.
             */
            score: number;
        };
        /**
         * TypeScore
         * @description 유형 하나의 일치도. 4개 유형 전체를 그래프로 보여줄 때 쓴다.
         */
        TypeScore: {
            /**
             * Key
             * @description 유형 키.
             * @enum {string}
             */
            key: "uraeok" | "uijeongbu" | "jangchungdong" | "dongchimi";
            /**
             * Name
             * @description 화면에 노출할 유형 이름.
             */
            name: string;
            /**
             * Match Score
             * @description 일치도(0.0~1.0). 내림차순으로 정렬되어 온다.
             */
            match_score: number;
        };
        /**
         * TypeSummary
         * @description 보조 유형(2순위·최원거리)에 쓰는 축약형. 화면에는 캐릭터와 이름만 노출된다.
         */
        TypeSummary: {
            /**
             * Key
             * @description 유형 키. 캐릭터 이미지 등 프론트 리소스를 고르는 기준으로 쓴다.
             * @enum {string}
             */
            key: "uraeok" | "uijeongbu" | "jangchungdong" | "dongchimi";
            /**
             * Name
             * @description 화면에 노출할 유형 이름. 예: `우래옥형`.
             */
            name: string;
            /**
             * Character Key
             * @description 캐릭터 이미지 키. 현재는 `key` 와 같은 값이 온다.
             */
            character_key: string;
            /**
             * Match Score
             * @description 이 유형과의 일치도(0.0~1.0). 백분율로 바꿔 표시한다.
             */
            match_score: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type HttpValidationError = components['schemas']['HTTPValidationError'];
export type PrimaryType = components['schemas']['PrimaryType'];
export type RecommendationAnswer = components['schemas']['RecommendationAnswer'];
export type RecommendationChoice = components['schemas']['RecommendationChoice'];
export type RecommendationQuestion = components['schemas']['RecommendationQuestion'];
export type RecommendationQuestionsResponse = components['schemas']['RecommendationQuestionsResponse'];
export type RecommendationResultResponse = components['schemas']['RecommendationResultResponse'];
export type RecommendationSubmitRequest = components['schemas']['RecommendationSubmitRequest'];
export type RecommendedRestaurant = components['schemas']['RecommendedRestaurant'];
export type TasteProfile = components['schemas']['TasteProfile'];
export type TraitScale = components['schemas']['TraitScale'];
export type TraitScore = components['schemas']['TraitScore'];
export type TypeScore = components['schemas']['TypeScore'];
export type TypeSummary = components['schemas']['TypeSummary'];
export type ValidationError = components['schemas']['ValidationError'];
export type $defs = Record<string, never>;
export interface operations {
    get_recommendation_questions_api_recommendation_questions__experience_level__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 문항 세트 종류. `beginner`(평양냉면이 처음인 사용자) 또는 `expert`(먹어본 적 있는 사용자). */
                experience_level: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationQuestionsResponse"];
                };
            };
            /** @description `experience_level` 이 `beginner` 도 `expert` 도 아닌 경우 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "지원하지 않는 경험 수준입니다."
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_recommendation_api_recommendation_submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendationSubmitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationResultResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
