//   npm run sync-tokens

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SOURCE_PATH = path.join(__dirname, "../tokens/figma-tokens.json");
const OUTPUT_PATH = path.join(__dirname, "../src/styles/tokens.css");

const TYPOGRAPHY_GROUPS = new Set([
  "headline",
  "title",
  "subtitle",
  "body",
  "caption",
  "label",
  "button",
]);

const NAME_FIXES = {
  defult: "default",
  deafult: "default",
  captione3: "caption3",
};

const slugify = (segment) =>
  (NAME_FIXES[segment] ?? segment).toLowerCase().replace(/\s+/g, "-");

function parseFont(value) {
  const match = value.match(
    /^Font\(family: "([^"]+)", style: [^,]+, size: ([\d.]+), weight: (\d+), lineHeight: ([\d.]+), letterSpacing: (-?[\d.]+)\)$/,
  );
  if (!match) return null;
  const [, family, size, weight, lineHeight, letterSpacing] = match;
  return {
    family,
    size: Math.round(parseFloat(size)),
    weight: parseInt(weight, 10),
    lineHeight: Math.round(parseFloat(lineHeight) * 1000) / 1000,
    letterSpacing: Math.round(parseFloat(letterSpacing) * 100) / 100,
  };
}

function buildColorVars(tokens) {
  const lines = [];

  for (const [key, value] of Object.entries(tokens)) {
    if (!key.startsWith("atomic/")) continue;
    const slug = key.split("/").slice(1).map(slugify).join("-");
    lines.push(`  --color-${slug}: ${value};`);
  }

  const semanticLines = [];
  for (const [key, value] of Object.entries(tokens)) {
    if (!key.startsWith("semantic/button/")) continue;
    const [, , propertyRaw, variant, state] = key.split("/");
    const property = propertyRaw === "background" ? "bg" : propertyRaw;
    semanticLines.push(
      `  --color-button-${slugify(variant)}-${property}-${slugify(state)}: ${value};`,
    );
  }

  return { colorLines: lines, semanticLines };
}

function buildTypographyVars(tokens) {
  const lines = [];
  const families = new Set();

  for (const [key, value] of Object.entries(tokens)) {
    const [group, rawName] = key.split("/");
    if (!TYPOGRAPHY_GROUPS.has(group)) continue;
    const font = parseFont(value);
    if (!font) continue;

    const name = slugify(rawName);
    families.add(font.family);
    // Tailwind's font-size namespace: --text-{name} is the font-size value,
    // and --text-{name}--{property} (double hyphen) composes the rest onto
    // the same `text-{name}` utility. See node_modules/tailwindcss/theme.css.
    lines.push(
      `  --text-${name}: ${font.size}px;`,
      `  --text-${name}--line-height: ${font.lineHeight};`,
      `  --text-${name}--letter-spacing: ${font.letterSpacing}px;`,
      `  --text-${name}--font-weight: ${font.weight};`,
    );
  }

  return { typographyLines: lines, families };
}

function main() {
  const tokens = JSON.parse(readFileSync(SOURCE_PATH, "utf-8"));
  const { colorLines, semanticLines } = buildColorVars(tokens);
  const { typographyLines, families } = buildTypographyVars(tokens);

  const fontLines = [...families].map(
    (family) => `  --font-${slugify(family)}: "${family}", sans-serif;`,
  );

  const css = `/* AUTO-GENERATED by scripts/sync-tokens.mjs — DO NOT EDIT BY HAND.
 * Source: tokens/figma-tokens.json
 * Regenerate with: npm run sync-tokens
 */

@theme {
  /* Colors: atomic */
${colorLines.join("\n")}

  /* Colors: semantic (button) */
${semanticLines.join("\n")}

  /* Typography */
${fontLines.join("\n")}
${typographyLines.join("\n")}
}
`;

  writeFileSync(OUTPUT_PATH, css);
  console.log(
    `Wrote ${colorLines.length} color, ${semanticLines.length} semantic, and ${typographyLines.length / 4} typography tokens to ${path.relative(process.cwd(), OUTPUT_PATH)}`,
  );
}

main();
